force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State Province</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CandidateTest.cls
@IsTest
public class CandidateTest{
    
    @IsTest
   public static void ZipCodeStateMatch(){
        Zip_Code__c zp=New Zip_Code__c();
        zp.Name='11757';
        zp.State__c='NY';
        insert zp;
       List<Candidate__c> cnList=New List<Candidate__c>();
      Candidate__c cnd=New Candidate__c();
        cnd.Name='Sila';
        cnd.Zip_Postal_Code__c='11757';
       cnList.add(cnd);
         MyCandidateHandler.CandidateStateUpdate(cnList);
        insert cnList;
       
        system.assert(cnd.State_Province__c==zp.State__c, 'State did not match');
    }
    
    

}