force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>Job Posting-{00000}</displayFormat>
        <label>Job Posting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Job_Posting_Site_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting_Site_Description__c</fullName>
    <label>Job Posting Site Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Position_Description__c.field-meta.xml
<CustomField>
    <fullName>Position_Description__c</fullName>
    <label>Position Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job_Posting_Site__c/Job_Posting_Site__c.object-meta.xml
<CustomObject>
    <label>Job Posting Site</label>
    <nameField>
        <label>Job Posting Site Name Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Posting Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>San Francisco, CA</fullName>
            </value>
            <value>
                <fullName>New York, NY</fullName>
            </value>
            <value>
                <fullName>Atlanta, GA</fullName>
            </value>
            <value>
                <fullName>London, United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Time</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Temp</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobPostingHandler.cls
public class JobPostingHandler  {
   
    Public Static Void JobPostingSiteDescription(List<Job_Posting__c> TN){
        Map<id,string> jobDesMap=new Map<id,string>();
        set<id> jobpostingId= new set<id>();
        
         for(Job_Posting__c job:TN){
          JobpostingId.add(job.Job_Posting_Site__c);       
         }
       
        
         List<Job_Posting_Site__c> jobPL=[Select Id,Name,URL__c,Owner.Name,isActive__c,CreatedDate 
                                   FROM Job_Posting_Site__c WHERE Id=:JobpostingId];  
          for(Job_Posting_Site__c jobP : jobPL){                         
                                              
                                               String str='Site Id: '+ jobP.Id+'\n'+
                     								      'Site Name: '+jobP.Name+ '\n'+
                                                          'Owner: '+jobP.Owner.Name+'\n'+
                     								      'URL: '+ jobP.URL__c+'\n'+
                     								      'Is Active: '+jobP.isActive__c+'\n'+
                     								      'Created on '+jobP.CreatedDate;
                     JobDesMap.put(jobP.Id,str);
}
        for(Job_Posting__c job:TN){ 
            job.Job_Posting_Site_Description__c = JobDesMap.get(job.Job_Posting_Site__c);
        }       
                                   }
    
    Public Static Void PositionDescription(List<Job_Posting__c> pTN) {
        Map<id,string> PosDesMap= new map<id,string>();
        set<id> posId= new set<id>();
        for(Job_Posting__c job:pTN) {
           posId.add(job.Position__c);
        }
   List<Position__c> jobPoL=[Select Id,Name,Owner.Name,CreatedDate,Start_Date__c,
                                   Status__c,Priority__c,Location__c,Type__c
                                   FROM Position__c WHERE Id in:posId];
        for(Position__c jobpo:jobPoL){
                              String str   	='Title: '+ jobpo.Name+'\n'+
                    						'Start Date: '+JobPo.Start_Date__c+'\n'+
                    						'Status: '+JobPo.Status__c+'\n'+
                    						'Priority: '+JobPo.Priority__c+'\n'+
                    						'Location: '+JobPo.Location__c+'\n'+
                    						'Type: '+JobPo.Type__c+'\n'+
                    						'Owner: '+JobPo.Owner.Name+'\n'+
                    						'Created Date'+JobPo.CreatedDate;
            PosDesMap.put(jobpo.id,str);
            }
        for(Job_Posting__c job:pTN) {
            job.Position_Description__c = PosDesMap.get(job.Position__c);
}
}

    }